In [1]:
import pandas as pd
import requests
from datetime import datetime
import pytz

In [2]:
tz = pytz.timezone('Europe/Berlin')
now = datetime.now().astimezone(tz)

now

datetime.datetime(2023, 7, 26, 21, 27, 0, 971487, tzinfo=<DstTzInfo 'Europe/Berlin' CEST+2:00:00 DST>)

In [3]:
def get_weather_loop(cities):

  API_key = '012bf1e02188785784af48c17d0f4eb9'

  tz = pytz.timezone('Europe/Berlin')
  now = datetime.now().astimezone(tz)

  weather_dict = {'city_id': [],
                'country': [],
                'forecast_time': [],
                'outlook': [],
                'weather_description': [],
                'temperature': [],
                'feels_like': [],
                'risk_of_rain': [],
                'rain': [],
                'snow': [],
                'wind_speed': [],
                'humidity': [],
                'information_retrieved_at': []}

  for city in cities:
    url = (f"http://api.openweathermap.org/data/2.5/forecast?q={city}&appid={API_key}&units=metric")
    response = requests.get(url)
    json = response.json()

    for i in json['list']:
        if city == 'Berlin':
            weather_dict['city_id'].append(1)
        elif city == 'Hamburg':
            weather_dict['city_id'].append(2)
        elif city == 'Frankfurt':
            weather_dict['city_id'].append(3)
        elif city == 'Munich':
            weather_dict['city_id'].append(4)
        elif city == 'Stuttgart':
            weather_dict['city_id'].append(5)
        elif city == 'Cologne':
            weather_dict['city_id'].append(6)
        elif city == 'Hannover':
            weather_dict['city_id'].append(7)

        weather_dict['country'].append(json['city']['country'])
        weather_dict['forecast_time'].append(i['dt_txt'])
        weather_dict['outlook'].append(i['weather'][0]['main'])
        weather_dict['weather_description'].append(i['weather'][0]['description'])
        weather_dict['temperature'].append(i['main']['temp'])
        weather_dict['feels_like'].append(i['main']['feels_like'])
        weather_dict['risk_of_rain'].append(i['pop'])
        try:
            weather_dict['rain'].append(i['rain']['3h'])
        except:
            weather_dict['rain'].append('0')
        try:
            weather_dict['snow'].append(i['snow']['3h'])
        except:
           weather_dict['snow'].append('0')
        weather_dict['wind_speed'].append(i['wind']['speed'])
        weather_dict['humidity'].append(i['main']['humidity'])
        weather_dict['information_retrieved_at'].append(now.strftime("%d/%m/%Y %H:%M:%S"))
        cities = ['Berlin', 'Hamburg', 'Frankfurt','Munich','Stuttgart','Cologne','Hannover']
  weather_df = pd.DataFrame(weather_dict)
  return weather_df

In [4]:
get_weather_loop(['Berlin', 'Hamburg', 'Frankfurt','Munich','Stuttgart','Cologne','Hannover'])

,city_id,country,forecast_time,outlook,weather_description,temperature,feels_like,risk_of_rain,rain,snow,wind_speed,humidity,information_retrieved_at
0,1,DE,2023-07-26 21:00:00,Clouds,few clouds,16.00,15.41,0.00,0,0,2.27,67,26/07/2023 21:27:20
1,1,DE,2023-07-27 00:00:00,Clouds,scattered clouds,14.65,14.08,0.00,0,0,3.17,73,26/07/2023 21:27:20
2,1,DE,2023-07-27 03:00:00,Clear,clear sky,12.23,11.70,0.00,0,0,2.71,84,26/07/2023 21:27:20
3,1,DE,2023-07-27 06:00:00,Clear,clear sky,15.71,15.09,0.00,0,0,3.42,67,26/07/2023 21:27:20
4,1,DE,2023-07-27 09:00:00,Clouds,overcast clouds,20.62,19.89,0.00,0,0,4.61,44,26/07/2023 21:27:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,7,DE,2023-07-31 06:00:00,Rain,light rain,16.19,16.19,0.66,0.26,0,5.64,89,26/07/2023 21:27:20
276,7,DE,2023-07-31 09:00:00,Rain,light rain,16.13,16.20,1.00,2.39,0,7.00,92,26/07/2023 21:27:20
277,7,DE,2023-07-31 12:00:00,Rain,moderate rain,15.63,15.57,1.00,4.05,0,8.64,89,26/07/2023 21:27:20
278,7,DE,2023-07-31 15:00:00,Rain,light rain,16.56,16.62,1.00,1.91,0,8.95,90,26/07/2023 21:27:20
279,7,DE,2023-07-31 18:00:00,Rain,light rain,16.45,16.50,1.00,0.22,0,7.90,90,26/07/2023 21:27:20

In [7]:
weather_df=get_weather_loop(['Berlin', 'Hamburg', 'Frankfurt','Munich','Stuttgart','Cologne','Hannover'])

In [8]:
weather_df

,city_id,country,forecast_time,outlook,weather_description,temperature,feels_like,risk_of_rain,rain,snow,wind_speed,humidity,information_retrieved_at
0,1,DE,2023-07-26 21:00:00,Clouds,few clouds,16.00,15.41,0.00,0,0,2.27,67,26/07/2023 21:28:32
1,1,DE,2023-07-27 00:00:00,Clouds,scattered clouds,14.65,14.08,0.00,0,0,3.17,73,26/07/2023 21:28:32
2,1,DE,2023-07-27 03:00:00,Clear,clear sky,12.23,11.70,0.00,0,0,2.71,84,26/07/2023 21:28:32
3,1,DE,2023-07-27 06:00:00,Clear,clear sky,15.71,15.09,0.00,0,0,3.42,67,26/07/2023 21:28:32
4,1,DE,2023-07-27 09:00:00,Clouds,overcast clouds,20.62,19.89,0.00,0,0,4.61,44,26/07/2023 21:28:32
...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,7,DE,2023-07-31 06:00:00,Rain,light rain,16.19,16.19,0.66,0.26,0,5.64,89,26/07/2023 21:28:32
276,7,DE,2023-07-31 09:00:00,Rain,light rain,16.13,16.20,1.00,2.39,0,7.00,92,26/07/2023 21:28:32
277,7,DE,2023-07-31 12:00:00,Rain,moderate rain,15.63,15.57,1.00,4.05,0,8.64,89,26/07/2023 21:28:32
278,7,DE,2023-07-31 15:00:00,Rain,light rain,16.56,16.62,1.00,1.91,0,8.95,90,26/07/2023 21:28:32
279,7,DE,2023-07-31 18:00:00,Rain,light rain,16.45,16.50,1.00,0.22,0,7.90,90,26/07/2023 21:28:32